set -g @gray_light  "#D8DEE9"
set -g @gray_medium "#ABB2BF"
set -g @gray_dark   "#3B4252"
set -g @green_soft  "#A3BE8C"
set -g @blue_muted  "#81A1C1"
set -g @cyan_soft   "#88C0D0"

set-option -g status-position top
set -g status-left-length 100
set -g status-style "fg=#{@gray_light},bg=default"
set -g status-left "#[fg=#{@green_soft},bold]#S #[fg=#{@gray_light},nobold]| "
set -g window-status-current-format "#[fg=#{@cyan_soft},bold] 󱟱 #[underscore]#I:#W"
set -g window-status-foramt " #I:#W"
set -g message-style "fg=#{@gray_light},bg=default"
set -g mode-style "fg=#{@gray_dark},bg=#{@blue_muted}"
set -g pane-border-stype "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@gray_medium}"
