# FONTS
font_family      family="MesloLGL Nerd Font Mono"
#font_family      family="Maple Mono"
font_size  	 13
bold_font        auto
italic_font      auto
bold_italic_font auto

#window
hide_window_decorations		titlebar-only
window_padding_wide		15
background_opacity		30
remember_window_size		yes

# tab bar
tab_bar_edge 		top
tab_bar_style 		powerline
tab_powerline_style	slanted

# animated cursor
cursor_trail 1
# END_KITTY_FONTS
